
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
platform :ios, '10.0'

target 'SimpleAppReactNative1' do
  project 'SimpleAppReactNative1',
  'DebugDev' => :debug,
  'ReleaseDev' => :release,
  'DebugStag' => :debug,
  'ReleaseStag' => :release,
  'DebugProd' => :debug,
  'ReleaseProd' => :release

  config = use_native_modules!
  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )

  target 'SimpleAppReactNative1Tests' do
    inherit! :complete
    # Pods for testing
  end

  use_native_modules!

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!(configurations: ['DebugDev', 'DebugProd', 'DebugStag'])
  post_install do |installer|
    # this is needed for Xcode 14, see more details here https://github.com/facebook/react-native/issues/34673
    # we should be able to remove this once CocoaPods catches up to it, see more details here https://github.com/CocoaPods/CocoaPods/issues/11402
    # https://github.com/facebook/react-native/pull/34826/files
    installer.target_installation_results.pod_target_installation_results.each do |pod_name, target_installation_result|
      if pod_name.to_s == 'React-Core'
          target_installation_result.resource_bundle_targets.each do |resource_bundle_target|
              resource_bundle_target.build_configurations.each do |config|
                  config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
              end
          end
      end
    end
    react_native_post_install(installer)
  end
end
